#!/bin/sh

# When udevtrigger actions the local filesystems are not neccesarily
# ready, so we re-trigger our nwfermi_daemon udev event

# make sure nwfermi_daemon starts
if [ -e /sbin/udevadm ]
then
    # opensuse does not have udevadm in the default path
    /sbin/udevadm trigger --action=change
else
    udevadm trigger --action=change
fi
