#!/bin/sh
# Copyright (C) 2002-2005 Flavio Stanchina
# Copyright (C) 2005-2006 Aric Cyr
# Copyright (C) 2007 Mario Limonciello
# Copyright (C) 2007 Alberto Milone



PKGVER=`dpkg-query -W -f='${Version}' nwfermi | awk -F "-" '{print $1}'`
PKGVER=${PKGVER#*:}

case "$1" in
    remove|upgrade)
		echo "Removing all DKMS Modules"
		dkms remove -m nwfermi -v $PKGVER --all > /dev/null
		echo "Done."
                systemctl disable nwfermi_module_dkms_updater.service
        ;;
esac


